apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-if2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth2",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "ranges": [
            [ {
                  "subnet": "192.168.1.0/29",
                  "rangeStart": "192.168.1.2",
                  "rangeEnd": "192.168.1.2"
            } ]
        ]
      }
  }'
