apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-if1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "ranges": [
            [ {
                  "subnet": "192.168.0.0/30",
                  "rangeStart": "192.168.0.1",
                  "rangeEnd": "192.168.0.1",
                  "routes": [
                    { "dst": "10.10.10.48/32" }
                  ],
                  "gateway": "1.1.1.1"
            } ]
        ]
      }
  }'
