apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-if1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "ranges": [
            [ {
                  "subnet": "10.10.254.0/28",
                  "rangeStart": "10.10.254.2",
                  "rangeEnd": "10.10.254.2"
            } ]
        ]
      }
  }'
