apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-if2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth2",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "ranges": [
            [ {
                  "subnet": "10.10.254.16/28",
                  "rangeStart": "10.10.254.18",
                  "rangeEnd": "10.10.254.18"
            } ]
        ]
      }
  }'
